### ISSUE TITLE
request for qthreads to install a pkg-config .pc file

### ISSUE THREAD

**Issue by mppf** [sandialabs/qthreads#107]
Over on the Chapel project we are trying to use pkg-config .pc files from the bundled third-party dependencies instead of libtool .la files. The reason we are doing this is that many package managers don't install .la files at all (see e.g. https://archlinux.org/news/operation-libtool-slay-in-testing/ ) and we are working towards having Chapel packages for more OSes. Today, the qthreads build produces a .la file. This is a request for the qthreads build/install to also produce a .pc file.

**Comment by mppf** [comment]
I do not have much experience generating .pc files but the file format is pretty simple. https://lists.freedesktop.org/archives/pkg-config/2007-August/000219.html has some suggestions for how to do it in an autotools project and https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing has some documentation about what to put in the .pc file. Of course you might find better resources in your own investigation.

**Comment by olivier-snl** [comment]
Hi @mppf. I wanted to ack this request for now to let you know I've seen it, since it is vacation season for my team -- @janciesko is out currently and I'll be out most of the next two weeks.  I read through the corresponding Chapel github issue to get some context just now, but we will need some time to look at the pkg-config generation documentation and assess.

**Comment by janciesko** [comment]
@mppf  - would adding cmake support to Qthreads alleviate this problem? This would likely require the upstream project to use cmake too.

**Comment by mppf** [comment]
For Chapel we are already requiring cmake but have only been using it for compiler builds. In principle, we could use cmake to build the qthreads bundled with Chapel if you move to cmake. (FWIW, for this issue, I would expect it to be simpler to manually generate a .pc file from a script than to migrate build systems)
