### ISSUE TITLE
stackleft Test Fails on Clang/Linux/X86_64

### ISSUE THREAD

**Issue by insertinterestingnamehere** [sandialabs/qthreads#144]
With clang versions 9 through 17 on x86_64 Linux the stackleft test fails.

I'll add more details as I find them here.

**Comment by janciesko** [comment]
See is the compiler optimizes things differently - we rely that the nested calls are not inlined.

**Comment by insertinterestingnamehere** [comment]
This one also hangs instead of fails some of the time.

**Comment by insertinterestingnamehere** [comment]
Seeing assertion fails in stackleft with clang/Linux/x86_64 as well, so following up on that may provide more info.

**Comment by insertinterestingnamehere** [comment]
This also fails on OSX/M1, so it's probably a clang thing. Enabling/disabling optimization passes didn't seem to help though.

**Comment by insertinterestingnamehere** [comment]
Also fails with icx.

**Comment by insertinterestingnamehere** [comment]
#176 makes it so that this succeeds with clang just like gcc. The fact that we have to suppress compiler optimizations around nested calls seems to indicate that something's still wrong so I'm leaving this open. The test failures are resolved though, so I'm lowering the priority of this issue.

**Comment by insertinterestingnamehere** [comment]
Okay, debugged this some more yesterday. No resolution so far, but I'm documenting what I found so I can do another pass on it later. With thread sanitizer enabled this test segfaults at really random times. As best I can tell, there isn't anything wrong with the stackleft API function itself though. Using `__builtin_frame_address(0)` to get the current stack pointer seems more likely to work reliably in all build environments/configurations, but swapping that in doesn't actually fix anything. The need to turn off optimizations isn't really anything deep, it's just a quirk of how this specific test works. The C standard doesn't really say anything about stack pointers, but we need the recursion in the test to not be inlined to make sure the routine works as expected.

Given that, I think the issue is more likely because that the way different qthreads wait on each other in this test is fairly unusual. Either the usage is just wrong or it's hitting some kind of bug that doesn't show up in other use-cases. I don't know which yet. It kind-of hinges on what our expectations are for if/how the main thread is supposed to participate in our schedulers and I haven't tracked down those details yet.

**Comment by insertinterestingnamehere** [comment]
Alright. I think we're okay closing this one now. Changing the optimization level is the right thing to do for this specific test. The C standard has no official notion of a stack pointer, but we still need to be able to probe info about it and test that because stacks are so central to the functionality we provide. This test *has* to constrain compiler optimization in some way to effectively test that what we're doing with stack pointers is correct and there is not an official standard way to do that.

The intermittent crash with thread sanitizer is resolved now in #243 as well though it wasn't actually related to the optimization issue.
