### ISSUE TITLE
Drop Support For Older Compilers

### ISSUE THREAD

**Issue by insertinterestingnamehere** [sandialabs/qthreads#167]
Currently there are various specializations in the code for compilers that are unlikely to work anyway since they haven't been tested in ages. Offhand I'm seeing pgi, sun, ibm, convey, and intel. I propose we drop support for these compilers and remove the related branching. The only exception to that should be Intel's new clang-based icx/icpx compilers since that's what they're planning on supporting moving forward.

**Comment by olivier-snl** [comment]
PGI and Sun could be removed.  There are still many production systems using legacy icc that will take time to migrate to icx.  We also use IBM POWER at times.

**Comment by insertinterestingnamehere** [comment]
icc still works so I've added it to CI.

**Comment by insertinterestingnamehere** [comment]
Fixed in #274.
