### ISSUE TITLE
Support ACFL?

### ISSUE THREAD

**Issue by insertinterestingnamehere** [sandialabs/qthreads#168]
Should we support the ARM Compiler For Linux (ACFL)? It's clang-based, so depending on how much has changed, whatever settings/ifdefs we have for clang may work with minimal changes. The latest release is from May 2023. It's based on LLVM 16.

**Comment by olivier-snl** [comment]
Ideally, yes.  In my experience the Arm compiler is indeed close to LLVM/Clang mainline, though the places that are different could impact us in the context switching, etc., where we do low-level programming.

**Comment by insertinterestingnamehere** [comment]
Sounds good. I think the image for https://hub.docker.com/r/armswdev/arm-compiler-for-linux/tags can be used to enable testing this in CI.

**Comment by insertinterestingnamehere** [comment]
I just confirmed that this builds locally without any needed changes, though there are a bunch of test failures to chase down. That may just be a build environment issue tho.

**Comment by insertinterestingnamehere** [comment]
Okay, I got it working in CI too. If we can get CircleCI set up on the main repo, then this will be resolved in https://github.com/sandialabs/qthreads/pull/163. The errors in the tests with acfl are all already covered in the other clang-related issues.
