### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by insertinterestingnamehere** [sandialabs/qthreads#241]
The Readme is very out of date. It references various architectures (e.g. Tilera) that are unlikely to work anymore. This should be fixed.

**Comment by olivier-snl** [comment]
Yes, this is an issue that has needed attention for some time.  We can also update the Qthreads web site accordingly.

**Comment by insertinterestingnamehere** [comment]
Fixed in https://github.com/sandialabs/qthreads/pull/287/commits/233bde8f699bbca0101ade21234a8b40e6a8b397
