### ISSUE TITLE
Use C11 thread_local

### ISSUE THREAD

**Issue by insertinterestingnamehere** [sandialabs/qthreads#275]
The current build system has a bunch of code for detecting what the appropriate keyword is to get thread-local storage. At this point we should really just be using the C11 `thread_local` storage duration though. It's very widely supported at this point.

**Comment by insertinterestingnamehere** [comment]
Fixed in https://github.com/sandialabs/qthreads/pull/289/commits/aa2849bd4cc6410b51ec876036099c767353ed66

**Comment by cho-m** [comment]
Was it intended to drop support for macOS? In Homebrew, we can no longer build qthreads as macOS does not support C11 threads (https://github.com/Homebrew/homebrew-core/pull/192437).

Based on gnulib[^1], threads.h is not available on:
* This header file is missing on many platforms: glibc 2.27, macOS 14, FreeBSD 9.3, NetBSD 8.0, OpenBSD 6.7, Minix 3.1.8, AIX 7.1, HP-UX 11.31, Solaris 11.3, Cygwin 2.2.x, mingw, MSVC 14, Android 9.0.

[^1]: https://www.gnu.org/software/gnulib/manual/html_node/threads_002eh.html

**Comment by insertinterestingnamehere** [comment]
Nope. Not intentional. That slipped through by mistake on my part. I missed that there were some new failures in our CI builds. I'll just revert it and update the release tarball.

That's super unfortunate that OSX is still not supporting this interface.

**Comment by insertinterestingnamehere** [comment]
Okay, the OSX-specific issues should now be fixed in https://github.com/sandialabs/qthreads/commit/a4ac8ee16d3ad0b56ec2b18eea850495efec908a as well. I've updated the release accordingly.

Thanks for letting us know so quickly about this! Given that, it didn't seem worth the trouble of doing a bugfix release. I've just updated the 1.21 release as-is.
