### ISSUE TITLE
Cache guard pages

### ISSUE THREAD

**Issue by ronawho** [sandialabs/qthreads#45]
Concurrent calls to mprotect seem to be particularly expensive on Xeon Phi. Qthreads pools stack memory, but not the guard pages, and it would make using guard pages much cheaper if they could also be pooled.

I think this is pretty straightforward, but if you need more details or context https://github.com/chapel-lang/chapel/pull/2849#issuecomment-155183504, https://github.com/chapel-lang/chapel/pull/2849#issuecomment-155523708, and https://chapel.atlassian.net/browse/CHAPEL-160 might be helpful.

This is a low priority item for us since we disable guard pages when optimizations are enabled. The extreme slowness of mprotect on Xeon Phi has caused us to disable guard pages for some correctness tests as well, but that's not a big deal.

**Comment by npe9** [comment]
I've already thrown a test into the main tree and begun to look at this. Is there anything you'd like me to prioritize more?

**Comment by olivier-snl** [comment]
I think their "Wish list" page gives an idea of the priority of their issues.

**Comment by npe9** [comment]
Yeah, once I figured out the relative classification, I labeled everything.

**Comment by ronawho** [comment]
Noting that this is still of interest to us, but is very low priority.

**Comment by ronawho** [comment]
`mprotect` was only particularly slow on Xeon Phi, and that's a dead architecture, so I don't think this is worthwhile anymore.
