### ISSUE TITLE
Add ability to specify explicit CPU bindings

### ISSUE THREAD

**Issue by ronawho** [sandialabs/qthreads#46]
This may be mostly finished with the "binders" work that @stelleg did, but we haven't gotten a chance to try binders out yet. This is mostly a placeholder issue to capture the gist of what we wanted as it may be helpful to anyone doing future development on binders. It'll probably also serve as a place to report bugs that we may run into as we start using binders.

The general idea is that instead of letting qthreads decide affinity, we want the ability to explicitly specify how shepherds/workers should bind to specific numa domains/CPUs. Something like OpenMP's [OMP_PLACES](https://gcc.gnu.org/onlinedocs/libgomp/OMP_005fPLACES.html#OMP_005fPLACES) or gomps [GOMP_CPU_AFFINITY](https://gcc.gnu.org/onlinedocs/libgomp/GOMP_005fCPU_005fAFFINITY.html#GOMP_005fCPU_005fAFFINITY)

We need this because parts of the Chapel runtime also have to reason about topology/affinity, and we need our runtime and qthreads to have the same "view" of the machine. For example with certain communication layers our runtime may pin memory to specific NUMA domains and we need to be sure our runtime and qthreads both agree on which socket is NUMA domain 0 and things like that.

This is a high priority item for us, although I don't think there's anything for the qthreads team to do until we've gotten a chance to try out the binders work.

**Comment by npe9** [comment]
Gotcha, if I can help with anything here, feel free to ping me.

**Comment by npe9** [comment]
@ronawho Have you tried out the binders stuff yet?

**Comment by ronawho** [comment]
We switched to binders by default in https://github.com/chapel-lang/chapel/pull/20901 and that has been working well for us
